ARMproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('entry/', views.Entry.as_view(), name='entry'), # after login where to go url.
    path('exit/', views.Exit.as_view(), name='exit'), # after logout where to go url.

    ## jobData App...
    path('jobData/', include('jobData.urls'), name='jobData'),

    ## jobVGM App...
    path('jobVGM/', include('jobVGM.urls'), name='jobVGM'),

    ## jobBOL App...
    path('jobBOL/', include('jobBOL.urls'), name='jobBOL'),

    ## jobACD App...
    path('jobACD/', include('jobACD.urls'), name='jobACD'),

    ## stuffingSheet App...
    path('stuffingSheet/', include('stuffingSheet.urls'), name='stuffingSheet'),

    ## jobOther App...
    path('jobOther/', include('jobOther.urls'), name='jobOther'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

jobACD/urls.py
from django.urls import path

from . import views

app_name = 'jobACD'

urlpatterns = [
    path('list', views.ACDformList.as_view(), name='acdList'),
    path('<int:pk>', views.ACDformDetails.as_view(), name='acdDetail'),
    path('<int:pk>/update', views.ACDformUpdate.as_view(), name='acdUpdate'),
    path('<int:pk>/acdForm/', views.AcdTemplate.as_view(), name='acdTemplate'),
    
    ## Function based Views...
    path('list/search/', views.search_view, name='search'),
]

jobBOL/urls.py
from django.urls import path

from . import views

app_name = 'jobBOL'

urlpatterns = [
    path('list', views.BOLformList.as_view(), name='bolList'),
    path('<int:pk>', views.BOLformDetails.as_view(), name='bolDetail'),
    path('<int:pk>/update', views.BOLformUpdate.as_view(), name='bolUpdate'),

    ## Function based Views...
    path('list/search/', views.search_view, name='search'),
    path('bolTemplate/', views.bol_template, name='bolTemplate'),
]

jobData/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'jobData'

urlpatterns = [
    ## Class Based Views....
    path('list', views.jobListView.as_view(), name='jobList'),
    path('<int:pk>', views.JobDetailView.as_view(), name='jobDetail'),
    path('', views.CreateJobView.as_view(), name='createJob'),
    path('<int:pk>/update', views.JobUpdateView.as_view(), name='updateJob'),
    path('<int:pk>/remove', views.JobDeleteView.as_view(), name='deleteJob'),

    ## Function Based Views....
    path('list/search/', views.search_view, name='search'),
    path('Filterlist/', views.jobFilterListView, name='jobFilterList'),
]

jobVGM/urls.py
from django.urls import path
from . import views

app_name = 'jobVGM'

urlpatterns = [
    # path('', views.VGMformView.as_view(), name='vgmForm'),
    path('list', views.VGMformList.as_view(), name='vgmList'),
    path('<int:pk>', views.VGMformDetails.as_view(), name='vgmDetail'),
    path('<int:pk>/update', views.VGMformUpdate.as_view(), name='vgmUpdate'),

    ## Function based Views...
    path('list/search/', views.search_view, name='search'),

    ## VGM Type form urls...
    path('type1/<int:pk>/form1', views.VgmForm1Detail.as_view(), name='type1Detail'),
    path('type2/<int:pk>/form2', views.VgmForm2Detail.as_view(), name='type2Detail'),
    path('type3/<int:pk>/form3', views.VgmForm3Detail.as_view(), name='type3Detail'),
    path('type4/<int:pk>/form4', views.VgmForm4Detail.as_view(), name='type4Detail'),
]

stuffingSheet/urls.py
from django.urls import path
from . import views

app_name = 'stuffingSheet'

urlpatterns = [
    path('list', views.StuffingSheetformList.as_view(), name='stuffingSheetList'),
    path('<int:pk>', views.StuffingSheetformDetails.as_view(), name='stuffingSheetDetail'),
    path('<int:pk>/update', views.StuffingSheetformUpdate.as_view(), name='stuffingSheetUpdate'),

    ## Function based Views...
    path('list/search/', views.search_view, name='search'),
    path('stuffingTemplate/', views.stuffingSheetTemplate, name='stuffingSheetTemplate'),
]

jobData/models.py
from datetime import date

from django.db import models
from django.urls import reverse

# Create your models here.
    
class DataOfJob(models.Model):

    index = models.IntegerField(primary_key=True)
    jobNumber = models.IntegerField()
    noOfBooking = models.IntegerField(default=1)
    container_no = models.CharField(max_length=255)
    shippingLine = models.CharField(max_length=255)
    Forwarder = models.CharField(max_length=255)
    bookingNum = models.CharField(max_length=255)
    exporterName = models.CharField(max_length=255)
    exporterAddress = models.CharField(max_length=255)
    size_20 = models.BooleanField('size=20', default=False)
    size_40 = models.BooleanField('size=40', default=False)
    tues_1 = models.IntegerField(default=0)
    tues_2 = models.IntegerField(default=0)
    totalTues_1 = models.IntegerField(default=0)
    totalTues_2 = models.IntegerField(default=0)
    todayDate = models.DateField(default=date.today)
    
    def save(self, *args, **kwargs):

        self.tues_1 = 0
        self.tues_2 = 0

        # Set values based on size_20 and size_40
        if self.size_20 and self.size_40:
            self.tues_1, self.tues_2 = 1, 2
        elif self.size_40:
            self.tues_2 = 2
        elif self.size_20:
            self.tues_1 = 1

        # Call the parent class save method
        super().save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse("jobData:jobList")
    
    def __str__(self):
        return str(self.index)

jobData/forms.py
from django import forms
from django.forms import ModelForm

from . import models


class NewData(ModelForm):

    jobNumber = forms.CharField(label='Job Number')
    noOfBooking = forms.IntegerField(label='No Of Booking')
    shippingLine = forms.CharField(label='Shipping Line')
    Forwarder = forms.CharField(label='Forwarder')
    bookingNum = forms.CharField(label='Booking No')
    exporterName = forms.CharField(label='Exporter Name')
    exporterAddress = forms.Textarea()

    class Meta:
        model = models.DataOfJob
        exclude = ['tues_1', 'tues_2', 'todayDate', 'totalTues_2', 'totalTues_1']
        widgets = {
            'size_20': forms.CheckboxInput(),
            'size_40': forms.CheckboxInput(),
            'exporterAddress': forms.Textarea(attrs={'rows': 5})
        }

    def clean(self):
        cleaned_data = super().clean()

        fields_to_uppercase = [
        'shippingLine', 'Forwarder', 'bookingNum', 'exporterName', 'exporterAddress'
        ]

        for field in fields_to_uppercase:
            if field is not None:
                cleaned_data[field] = cleaned_data.get(field, '').upper()

jobData/views.py
from datetime import date, datetime
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Sum
from django.db.models.query import QuerySet
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from jobACD.forms import AcdForm
from jobACD.models import AcdModel
from jobBOL.forms import BolForm
from jobBOL.models import BolModel
from jobData.forms import NewData
from jobData.models import DataOfJob
from jobOther.forms import OtherForm
from jobOther.models import OtherModel
from jobVGM.forms import BillingForm
from jobVGM.models import VgmModel
from stuffingSheet.forms import StuffingSheetForm
from stuffingSheet.models import StuffingSheetModel

# Create your views here.

## Class Based Views....

class jobListView(ListView):
    model = DataOfJob
    context_object_name = 'showJobList'

class CreateJobView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'jobData/dataofjob_detail.html'
    model = DataOfJob
    form_class = NewData

    def form_valid(self, form):
        # Get the number of bookings from the form
        num_bookings = form.cleaned_data.get('noOfBooking')

        # Retrieve the data for each booking
        original_job_data = {
            'jobNumber': form.cleaned_data.get('jobNumber'),
            'noOfBooking': 1,  # Set to 1 because this will be individual booking now
            'container_no': form.cleaned_data.get('container_no'),
            'shippingLine': form.cleaned_data.get('shippingLine'),
            'Forwarder': form.cleaned_data.get('Forwarder'),
            'bookingNum': form.cleaned_data.get('bookingNum'),
            'exporterName': form.cleaned_data.get('exporterName'),
            'exporterAddress': form.cleaned_data.get('exporterAddress'),
            'size_20': form.cleaned_data.get('size_20'),
            'size_40': form.cleaned_data.get('size_40'),
            'todayDate': form.cleaned_data.get('todayDate', timezone.now().date()),
        }

        for _ in range(num_bookings):
            # Create a new instance with the same data but a new primary key
            self.object = DataOfJob(**original_job_data)
            self.object.pk = None  # This creates a new instance with a new primary key
            self.object.save()  # Save the new instance

            # Define size_20 and size_40 based on the tues_1 and tues_2 values
            size_20 = self.object.size_20
            size_40 = self.object.size_40

            # Create instances for related models
            VgmModel.objects.create(
                jobNumber = self.object.jobNumber,
                containerNum = self.object.container_no,
                exporterName=self.object.exporterName,
                exporterAddress=self.object.exporterAddress,
                size_20=size_20,
                size_40=size_40,
                bookingNum=self.object.bookingNum,
            )

            BolModel.objects.create(
                jobNumber = self.object.jobNumber,
                containerNum = self.object.container_no,
                shippingLine=self.object.shippingLine,
                bookingNum=self.object.bookingNum,
                exporterName=self.object.exporterName,
                exporterAddress=self.object.exporterAddress,
            )

            AcdModel.objects.create(
                jobNumber = self.object.jobNumber,
                containerNum = self.object.container_no,
                bookingNum=self.object.bookingNum,
                exporterName=self.object.exporterName,
                exporterAddress=self.object.exporterAddress,
            )

            StuffingSheetModel.objects.create(
                jobNumber = self.object.jobNumber,
                containerNum = self.object.container_no,
                bookingNum=self.object.bookingNum,
                exporterName=self.object.exporterName,
                shippingLine=self.object.shippingLine,
                size_20=size_20,
                size_40=size_40,
            )

            OtherModel.objects.create(
                jobNumber = self.object.jobNumber,
                containerNum = self.object.container_no,
                bookingNum=self.object.bookingNum,
            )

        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Fetch unique Exporter info from the database and add them to the context
        context['unique_exporterName'] = DataOfJob.objects.values_list('exporterName', flat=True).distinct()
        context['unique_exporterAddress'] = DataOfJob.objects.values_list('exporterAddress', flat=True).distinct()
        context['unique_Forwarder'] = DataOfJob.objects.values_list('Forwarder', flat=True).distinct()
        context['unique_bookingNum'] = DataOfJob.objects.values_list('bookingNum', flat=True).distinct()

        return context


class JobDetailView(DetailView):
    model = DataOfJob
    context_object_name = 'showJobDetail'
    template_name = 'jobData/dataofjob_detail.html'


class JobUpdateView(LoginRequiredMixin, UpdateView):
    model = DataOfJob
    form_class = NewData
    login_url = '/login/'
    redirect_field_name = 'jobData/dataofjob_detail.html'

    # def form_valid(self, form):
    #     response = super().form_valid(form)
    #     size_20 = self.object.size_20
    #     size_40 = self.object.size_40

    #     # Create instances for related models
    #     VgmModel.objects.create(
    #         jobNumber = self.object.jobNumber,
    #         exporterName=self.object.exporterName,
    #         exporterAddress=self.object.exporterAddress,
    #         size_20=size_20,
    #         size_40=size_40,
    #         bookingNum=self.object.bookingNum,
    #     )

    #     BolModel.objects.create(
    #         jobNumber = self.object.jobNumber,
    #         shippingLine=self.object.shippingLine,
    #         bookingNum=self.object.bookingNum,
    #         exporterName=self.object.exporterName,
    #         exporterAddress=self.object.exporterAddress,
    #     )

    #     AcdModel.objects.create(
    #         jobNumber = self.object.jobNumber,
    #         bookingNum=self.object.bookingNum,
    #         exporterName=self.object.exporterName,
    #         exporterAddress=self.object.exporterAddress,
    #     )

    #     StuffingSheetModel.objects.create(
    #         jobNumber = self.object.jobNumber,
    #         bookingNum=self.object.bookingNum,
    #         exporterName=self.object.exporterName,
    #         shippingLine=self.object.shippingLine,
    #         size_20=size_20,
    #         size_40=size_40,
    #     )

    #     OtherModel.objects.create(
    #         jobNumber = self.object.jobNumber,
    #         bookingNum=self.object.bookingNum,
    #     )

    #     return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Fetch unique Exporter info from the database and add them to the context
        context['unique_exporterName'] = DataOfJob.objects.values_list('exporterName', flat=True).distinct()
        context['unique_exporterAddress'] = DataOfJob.objects.values_list('exporterAddress', flat=True).distinct()
        context['unique_Forwarder'] = DataOfJob.objects.values_list('Forwarder', flat=True).distinct()
        context['unique_bookingNum'] = DataOfJob.objects.values_list('bookingNum', flat=True).distinct()

        return context
    

class JobDeleteView(LoginRequiredMixin, DeleteView):
    model = DataOfJob
    success_url = reverse_lazy('jobData:jobList')



## Function Based Views....................................................


def totalTues(from_date, to_date):
    # Convert date strings to datetime objects
    from_date_obj = datetime.strptime(from_date, "%Y-%m-%d")
    to_date_obj = datetime.strptime(to_date, "%Y-%m-%d")

    # Calculate the sum of tues_1 and tues_2 between the given date range
    total_tues = DataOfJob.objects.filter(todayDate__range=[from_date_obj, to_date_obj]).aggregate(
        total_tues_1=Sum('tues_1'),
        total_tues_2=Sum('tues_2')
    )

    # Access the sums from the result
    sum_tues_1 = total_tues['total_tues_1'] or 0
    sum_tues_2 = total_tues['total_tues_2'] or 0

    return sum_tues_1, sum_tues_2



def jobFilterListView(request):
    from_date_str = request.POST.get('from_date', '')
    to_date_str = request.POST.get('to_date', '')

    if from_date_str != '' and to_date_str != '':

        totalTues1, totalTues2 = totalTues(from_date_str, to_date_str)
        total_tues = totalTues1 + totalTues2
        
        context = {
            'from_date_str':from_date_str,
            'to_date_str':to_date_str,
            'total_tues':total_tues
        }
    else:
        context = {
            'from_date_str':'',
            'to_date_str':'',
            'total_tues':'',
        }
    # totalTues1, totalTues2 = totalTues(query_conditions)

    return render(request, 'jobData/jobFilterList.html', context)



def search_view(request):
    query = request.GET.get('search', '') 
    
    search_fields = [
    'jobNumber',
    'shippingLine',
    'Forwarder',
    'bookingNum',
    'size_20',
    'size_40',
    'tues_1',
    'tues_2',
    'exporterName',
    'exporterAddress',
    ]

    # Create an empty Q object to accumulate conditions
    query_conditions = Q()

    # Loop through each field and add an OR condition
    for field in search_fields:
        query_conditions |= Q(**{f'{field}__icontains': query})

    # Use the accumulated Q object in the filter
    results = DataOfJob.objects.filter(query_conditions)

jobData/templates/jobData/dataofjob_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ dataOfJob.jobNumber }}?</p>
    <input type="submit" class="btn btn-danger" name="" id="Confirm">
</form>

{% endblock %}

jobData/templates/jobData/dataofjob_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>Details of Job: {{ showJobDetail.jobNumber }}</h2>

<hr>
<br>
<!-- showJobDetail -->
<h4>For Job:</h4>

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">S no</th>
        <th scope="col">Job Number</th>
        <!-- <th scope="col">No Of Booking</th> -->
        <th scope="col">Shipping Line</th>
        <th scope="col">Forwarder</th>
        <th scope="col">Booking Number</th>
        <th scope="col">Size of 20</th>
        <th scope="col">Size of 40</th>
        <th scope="col">Tues of 20</th>
        <th scope="col">Tues of 40</th>
        <th scope="col">Exporter Name</th>
        <th scope="col">Exporter Address</th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ showJobDetail.jobNumber }}</td>
            <!-- <td>{{ showJobDetail.noOfBooking }}</td> -->
            <td>{{ showJobDetail.shippingLine }}</td>
            <td>{{ showJobDetail.Forwarder }}</td>
            <td>{{ showJobDetail.bookingNum }}</td>

            {% if showJobDetail.size_20 == True and showJobDetail.size_40 == True %}
              <td>20</td>
              <td>40</td>
            {% elif showJobDetail.size_20 == True and showJobDetail.size_40 == False %}
              <td>20</td>
              <td>0</td>
            {% elif showJobDetail.size_20 == False and showJobDetail.size_40 == True %}
              <td>0</td>
              <td>40</td>
            {% endif %}
            
            <td>{{ showJobDetail.tues_1 }}</td>
            <td>{{ showJobDetail.tues_2 }}</td>
            <td>{{ showJobDetail.exporterName }}</td>
            <td>{{ showJobDetail.exporterAddress }}</td>
        </tr>
    </tbody>
</table>
<div class="d-grid gap-2 d-md-flex justify-content-md">
  <a href="{% url 'jobData:updateJob' pk=showJobDetail.pk %}"><button class="btn btn-success me-md-2" type="button">Update</button></a>
  <a href="{% url 'jobData:deleteJob' pk=showJobDetail.pk %}"><button class="btn btn-danger" type="button">Remove</button></a>
</div>

<br>
<hr>
<div class="d-grid gap-2 d-md-flex justify-content-md">
<br>

    <a href="{% url 'jobVGM:vgmUpdate' pk=showJobDetail.pk %}"><button class="btn btn-info" type="button">VGM Form</button></a>
    <a href="{% url 'jobBOL:bolUpdate' pk=showJobDetail.pk %}"><button class="btn btn-info" type="button">Bill of Landing Form</button></a>
    <a href="{% url 'jobACD:acdUpdate' pk=showJobDetail.pk %}"><button class="btn btn-info" type="button">ACD Form</button></a>
    <a href="{% url 'stuffingSheet:stuffingSheetUpdate' pk=showJobDetail.pk %}"><button class="btn btn-info" type="button">Stuffing Sheet</button></a>
<!-- </div> -->
</div>
<hr>


{% endblock %}

jobData/templates/jobData/dataofjob_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <div  style="height: 60vh;">
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="submit" value="Submit" class="btn btn-primary pd-10">
        <br><br><br><br>
    </form>
</div>

{% include 'bases/jobDataBase.html' %}

{% endblock %}

jobData/templates/jobData/dataofjob_list.html
{% extends 'base.html' %}

{% block content %}
<form method="GET" action="{% url 'jobData:search' %}" class="d-flex" role="search">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" id="search">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>

<br>

<a class="btn btn-success" href="{% url 'jobData:jobFilterList' %}" role="button">
  Filter
</a>

<br><br>

<h2>List of the job</h2>

<br>
<!-- showJobList -->
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">S no</th>
        <th scope="col">Job Number</th>
        <!-- <th scope="col">No Of Booking</th> -->
        <th scope="col">Shipping Line</th>
        <th scope="col">Forwarder</th>
        <th scope="col">Booking Number</th>
        <th scope="col">Size of 20</th>
        <th scope="col">Size of 40</th>
        <th scope="col">Tues of 20</th>
        <th scope="col">Tues of 40</th>
        <th scope="col">Exporter Name</th>
        <th scope="col">Exporter Address</th>
      </tr>
    </thead>
    <tbody>
        {% for items in showJobList %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'jobData:jobDetail' pk=items.pk %}" class="link-opacity-25-hover">{{ items.jobNumber }}</a></td>
                <!-- <td>{{ items.noOfBooking }}</td> -->
                <td>{{ items.shippingLine }}</td>
                <td>{{ items.Forwarder }}</td>
                <td>{{ items.bookingNum }}</td>
                <td>{{ items.size_20 }}</td>
                <td>{{ items.size_40 }}</td>
                <td>{{ items.tues_1 }}</td>
                <td>{{ items.tues_2 }}</td>
                <td>{{ items.exporterName }}</td>
                <td>{{ items.exporterAddress }}</td>
            </tr>
        {% endfor %}
    </tbody>
  </table>

{% endblock %}

jobData/templates/jobData/jobFilterList.html
{% extends 'base.html' %}

{% block content %}

<h5><u>Enter the Dates</u></h5>
    <div class="container"><br>
        <form method="POST" style="width: 300px;" action="{% url 'jobData:jobFilterList' %}">
            
            <div class="mb-3">
              <label class="form-label fw-semibold">From</label>
              <input type="date" class="form-control" name="from_date">
            </div>

            <div class="mb-3">
              <label class="form-label fw-semibold">To</label>
              <input type="date" class="form-control" name="to_date">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>

            {% csrf_token %}
        </form><br>
    </div>
    <hr>

    <div class="container">
        <h3>Filtered Data</h3>

        <table class="table border">
            <tbody>
                <tr>
                    <td class="border border-dark">From</td>
                    <td class="border border-dark">To</td>
                    <td class="border border-dark">Total Tues</td>
                </tr>
                <tr>
                    <td class="border border-dark">{{ from_date_str }}</td>
                    <td class="border border-dark">{{ to_date_str }}</td>
                    <td class="border border-dark">{{ total_tues }}</td>
                </tr>
            </tbody>
        </table>
        
    </div>
{% endblock %}

jobData/templates/jobData/search.html
{% extends 'base.html' %}

{% block content %}

<h3>Searched Results</h3>
<hr>
    {% if results %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">S no</th>
                    <th scope="col">Job Number</th>
                    <th scope="col">No Of Booking</th>
                    <th scope="col">Shipping Line</th>
                    <th scope="col">Forwarder</th>
                    <th scope="col">Booking Number</th>
                    <th scope="col">Size of 20</th>
                    <th scope="col">Size of 40</th>
                    <th scope="col">Tues of 20</th>
                    <th scope="col">Tues of 40</th>
                    <th scope="col">Exporter Name</th>
                    <th scope="col">Exporter Address</th>
                </tr>
            </thead>
            <tbody>
                {% for job in results %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'jobVGM:vgmDetail' pk=job.pk %}" class="link-opacity-25-hover">{{ job.jobNumber }}</a></td>
                        <td>{{ job.noOfBooking }}</td>
                        <td>{{ job.shippingLine }}</td>
                        <td>{{ job.Forwarder }}</td>
                        <td>{{ job.bookingNum }}</td>
                        <td>{{ job.size_20 }}</td>
                        <td>{{ job.size_40 }}</td>
                        <td>{{ job.tues_1 }}</td>
                        <td>{{ job.tues_2 }}</td>
                        <td>{{ job.exporterName }}</td>
                        <td>{{ job.exporterAddress }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No results found.</p>
    {% endif %}

{% endblock %}