ARMproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('entry/', views.Entry.as_view(), name='entry'), # after login where to go url.
    path('exit/', views.Exit.as_view(), name='exit'), # after logout where to go url.

    ## jobData App...
    path('jobData/', include('jobData.urls'), name='jobData'),

    ## jobVGM App...
    path('jobVGM/', include('jobVGM.urls'), name='jobVGM'),

    ## jobBOL App...
    path('jobBOL/', include('jobBOL.urls'), name='jobBOL'),

    ## jobACD App...
    path('jobACD/', include('jobACD.urls'), name='jobACD'),

    ## stuffingSheet App...
    path('stuffingSheet/', include('stuffingSheet.urls'), name='stuffingSheet'),

    ## jobOther App...
    path('jobOther/', include('jobOther.urls'), name='jobOther'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

jobACD/urls.py
from django.urls import path

from . import views

app_name = 'jobACD'

urlpatterns = [
    path('list', views.ACDformList.as_view(), name='acdList'),
    path('<int:pk>', views.ACDformDetails.as_view(), name='acdDetail'),
    path('<int:pk>/update', views.ACDformUpdate.as_view(), name='acdUpdate'),
    path('<int:pk>/acdForm/', views.AcdTemplate.as_view(), name='acdTemplate'),
    
    ## Function based Views...
    path('list/search/', views.search_view, name='search'),
]

jobBOL/urls.py
from django.urls import path

from . import views

app_name = 'jobBOL'

urlpatterns = [
    path('list', views.BOLformList.as_view(), name='bolList'),
    path('<int:pk>', views.BOLformDetails.as_view(), name='bolDetail'),
    path('<int:pk>/update', views.BOLformUpdate.as_view(), name='bolUpdate'),

    ## Function based Views...
    path('list/search/', views.search_view, name='search'),
    path('bolTemplate/', views.bol_template, name='bolTemplate'),
]

jobData/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'jobData'

urlpatterns = [
    ## Class Based Views....
    path('list', views.jobListView.as_view(), name='jobList'),
    path('<int:pk>', views.JobDetailView.as_view(), name='jobDetail'),
    path('', views.CreateJobView.as_view(), name='createJob'),
    path('<int:pk>/update', views.JobUpdateView.as_view(), name='updateJob'),
    path('<int:pk>/remove', views.JobDeleteView.as_view(), name='deleteJob'),

    ## Function Based Views....
    path('list/search/', views.search_view, name='search'),
    path('Filterlist/', views.jobFilterListView, name='jobFilterList'),
]

jobVGM/urls.py
from django.urls import path
from . import views

app_name = 'jobVGM'

urlpatterns = [
    # path('', views.VGMformView.as_view(), name='vgmForm'),
    path('list', views.VGMformList.as_view(), name='vgmList'),
    path('<int:pk>', views.VGMformDetails.as_view(), name='vgmDetail'),
    path('<int:pk>/update', views.VGMformUpdate.as_view(), name='vgmUpdate'),

    ## Function based Views...
    path('list/search/', views.search_view, name='search'),

    ## VGM Type form urls...
    path('type1/<int:pk>/form1', views.VgmForm1Detail.as_view(), name='type1Detail'),
    path('type2/<int:pk>/form2', views.VgmForm2Detail.as_view(), name='type2Detail'),
    path('type3/<int:pk>/form3', views.VgmForm3Detail.as_view(), name='type3Detail'),
    path('type4/<int:pk>/form4', views.VgmForm4Detail.as_view(), name='type4Detail'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ARM Agency</title>

    <!-- JS link -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Custon links -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    <style>
      /* Custom styles for adjusting row height in the table */
      .custom-table tbody tr.row2 {
          height: 100px; /* Set your desired height for Row 2 */
      }
  </style>

</head>

<body>
  <!-- Header Navbar -->

  <nav class="navbar fixed-top navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">ARM Agency</a>
      
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">

        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Here</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
      
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            {% if user.is_authenticated %}

                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'jobData:createJob' %}">New Job</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'jobData:jobList' %}">Job List</a>
                </li>      

                <!-- DropDown  -->
                <li class="nav-item">
                  <div class="dropdown">
                    <button class="nav-link active dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                      More
                    </button>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'jobVGM:vgmList' %}">VGM List</a></li>
                      <li><a class="dropdown-item" href="{% url 'jobBOL:bolList' %}">BL List</a></li>
                      <li><a class="dropdown-item" href="{% url 'jobACD:acdList' %}">ACD List</a></li>
                      <li><a class="dropdown-item" href="{% url 'stuffingSheet:stuffingSheetList' %}">Stuffing Sheet</a></li>
                      <li><a class="dropdown-item" href="{% url 'jobOther:otherList' %}">Extended Data</a></li>
                    </ul>
                  </div>
                </li>  

            {% if user.is_authenticated and user.is_superuser %}
                <li>
                  <a class="nav-link active me-auto fw-semibold" href="{% url 'accounts:signup' %}">Signup</a>
                </li>

            {% endif %}
                <!-- <li>
                  <a class="nav-link active fw-semibold" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
                </li> -->
                <form action="{% url 'logout' %}" method="POST">
                  {% csrf_token %}
          
                  {% if messages %}
                  {% for message in messages %}
          
                  <div class="alert
                  {% if message.tags == 'error' %} alert-danger
                  {% elif message.tags == 'success' %} alert-success
                  {% else %} alert-warning
                  {% endif %} alert-dismissible fade show"
                  role="alert">
                      {{ message }}
                      <button type="button" class="nav-link active me-auto fw-semibold" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
          
                  {% endfor %}
                  {% endif %}
          
                  <button type="submit" class="nav-link active me-auto fw-semibold">Logout</button>
              </form>

            {% else %}
                <li class="nav-item">
                  <a class="nav-link active fw-semibold" aria-current="page" href="{% url 'accounts:login' %}">Login</a></li>
                </li>

            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </nav>


  <br><br><br>
  <!-- Content Block -->
    <div class="container">
      {% block content %}
      
      {% endblock %}
    </div>
</body>
</html>

templates/entry.html
{% extends 'base.html' %}

{% block content %}
{% include 'bases/indexBase.html' %}
    <br><br><br>
    <p class="p-6 fw-bold font-monospace">
        ARM Agency is a distinguished agency specializing in custom clearance services, ensuring smooth and efficient import
        and export processes. Our commitment to excellence has earned us a reputation for providing one of the best custom
        clearance services in the industry. We handle customs clearance not only within India but also for shipments to
        various foreign countries, handling large volumes of goods with precision and expertise. Our approach is rooted in
        trust and wisdom, ensuring that every clearance process is conducted with integrity and foresight, navigating
        through customs regulations and procedures seamlessly. With over 25 years of experience in the custom clearance
        business, ARM Agency stands as a trusted partner for businesses seeking reliable and hassle-free customs clearance
        services.
    </p>

{% endblock %}

templates/exit.html
{% extends 'base.html' %}

{% block content %}
{% include 'bases/indexBase.html' %}
    <h2>You have logged out!!
        <br>
    </h2>

    <h5><br>
        <p>Thankyou for visiting :)</p>
    </h5>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    
    {% include 'bases/indexBase.html' %}
    <br>
    <h1>Welcome  :)</h1>
{% endblock %}