ARMproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('entry/', views.Entry.as_view(), name='entry'), # after login where to go url.
    path('exit/', views.Exit.as_view(), name='exit'), # after logout where to go url.

    ## jobData App...
    path('jobData/', include('jobData.urls'), name='jobData'),

    ## jobVGM App...
    path('jobVGM/', include('jobVGM.urls'), name='jobVGM'),

    ## jobBOL App...
    path('jobBOL/', include('jobBOL.urls'), name='jobBOL'),

    ## jobACD App...
    path('jobACD/', include('jobACD.urls'), name='jobACD'),

    ## stuffingSheet App...
    path('stuffingSheet/', include('stuffingSheet.urls'), name='stuffingSheet'),

    ## jobOther App...
    path('jobOther/', include('jobOther.urls'), name='jobOther'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

jobACD/urls.py
from django.urls import path

from . import views

app_name = 'jobACD'

urlpatterns = [
    path('list', views.ACDformList.as_view(), name='acdList'),
    path('<int:pk>', views.ACDformDetails.as_view(), name='acdDetail'),
    path('<int:pk>/update', views.ACDformUpdate.as_view(), name='acdUpdate'),
    path('<int:pk>/acdForm/', views.AcdTemplate.as_view(), name='acdTemplate'),
    
    ## Function based Views...
    path('list/search/', views.search_view, name='search'),
]

jobBOL/urls.py
from django.urls import path

from . import views

app_name = 'jobBOL'

urlpatterns = [
    path('list', views.BOLformList.as_view(), name='bolList'),
    path('<int:pk>', views.BOLformDetails.as_view(), name='bolDetail'),
    path('<int:pk>/update', views.BOLformUpdate.as_view(), name='bolUpdate'),

    ## Function based Views...
    path('list/search/', views.search_view, name='search'),
    path('bolTemplate/', views.bol_template, name='bolTemplate'),
]

jobACD/models.py
from datetime import date

from django.db import models
from django.urls import reverse
from jobData.models import DataOfJob

# Create your models here.

class AcdModel(models.Model):

    index = models.ForeignKey(DataOfJob, on_delete=models.CASCADE, primary_key=True)
    jobNumber = models.IntegerField(blank=True, null=True, default=0)
    exporterAddress = models.CharField(default='Exporter Address', blank=True, null=True, max_length=255)
    bookingNum = models.CharField(default='Booking Num', blank=True, null=True, max_length=255)
    consignee = models.CharField(default='Consignee', blank=True, null=True, max_length=255)
    nameOfOceanCarrier = models.CharField(default='Name Of Ocean Carrier', blank=True, null=True, max_length=255)
    vesselName = models.CharField(default='Vessel Name', blank=True, null=True, max_length=255)
    placeOfReceiptOfGood = models.CharField(default='Place Of Receipt Of Good', blank=True, null=True, max_length=255)
    portOfLoading = models.CharField(default='Port Of Loading', blank=True, null=True, max_length=255)
    portOfDischarge = models.CharField(default='Port Of Discharge', blank=True, null=True, max_length=255)
    placeOfDeliveryWithStateCode = models.CharField(default='Place Of Delivery', blank=True, null=True, max_length=255)
    containerNum = models.CharField(default='Container Num', blank=True, null=True, max_length=255)
    customSeal = models.IntegerField(default=0, blank=True, null=True, max_length=255)
    shippingBillNo = models.IntegerField(default=0, blank=True, null=True)
    marks = models.CharField(default='Marks', blank=True, null=True, max_length=255)
    noOfPkgs = models.IntegerField(default=0, blank=True, null=True)
    fullCommondityDescription = models.CharField(default='Description', max_length=255, blank=True, null=True)
    grossWt = models.FloatField(default=0.0, blank=True, null=True)
    htsCode = models.IntegerField(default=0, blank=True, null=True)
    placeOfIssueOfCargo = models.CharField(default='Issue Of Cargo', max_length=255, blank=True, null=True)
    dateOfIssueOfCargo = models.DateField(default=date.today, blank=True, null=True)
    exporterName = models.CharField(default='Exporter Name', blank=True, null=True, max_length=255)
    NameOfAuthorised = models.CharField(default='Name Of Authorised', max_length=255, blank=True)
    signatureImg = models.ImageField(upload_to='signature_pic/%y', blank=True, null=True)

    def __str__(self):
        return str(self.index)
    
    def get_absolute_url(self):
        return reverse('jobACD:acdDetail', kwargs={'pk': self.pk})

jobACD/forms.py
from django import forms
from django.forms import ModelForm

from .models import AcdModel


class AcdForm(ModelForm):
    jobNumber = forms.IntegerField(label='Job Number')
    bookingNum = forms.CharField(label='Booking Num')
    exporterAddress = forms.Textarea()
    consignee = forms.CharField(required=False, label='Consignee')
    nameOfOceanCarrier = forms.CharField(required=False, label='Name Of Ocean Carrier')
    vesselName = forms.CharField(required=False, label='Vessel Name')
    placeOfReceiptOfGood = forms.CharField(required=False, label='Place Of Receipt Of Good')
    portOfLoading = forms.CharField(required=False, label='Port Of Loading')
    portOfDischarge = forms.CharField(required=False, label='Port Of Discharge')
    placeOfDeliveryWithStateCode = forms.CharField(required=False, label='Place Of Delivery With State Code')
    containerNum = forms.CharField(required=False, label='Container Num')
    customSeal = forms.IntegerField(required=False, label='Custom Seal')
    shippingBillNo = forms.IntegerField(required=False, label='Shipping Bill No')
    marks = forms.CharField(required=False, label='Marks')
    noOfPkgs = forms.IntegerField(required=False, label='No Of Pkgs')
    fullCommondityDescription = forms.CharField(required=False, label='Full Commondity Description')
    grossWt = forms.FloatField(required=False, label='Gross Wt')
    htsCode = forms.IntegerField(required=False, label='HTC Code')
    placeOfIssueOfCargo = forms.CharField(required=False, label='place Of Issue Of Cargo')
    dateOfIssueOfCargo = forms.DateField(required=False, label='Date Of Issue Of Cargo')
    exporterName = forms.CharField(required=False, label='Exporter Name')
    NameOfAuthorised = forms.CharField(required=False, label='Name Of Authorised')
    signatureImg = forms.ImageField(required=False, label='Signature Img')

    class Meta:
        model = AcdModel
        fields = '__all__'
        widgets = {'dateOfIssueOfCargo': forms.DateInput(attrs={'type':'date'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['dateOfIssueOfCargo'].input_formats = ["%Y-%m-%d"]
        self.fields['dateOfIssueOfCargo'].label = 'Date Of Issue Of Cargo'

    def clean(self):
        cleaned_data = super().clean()

        fields_to_uppercase = [
        'bookingNum', 'exporterAddress', 'consignee',
        'nameOfOceanCarrier', 'vesselName', 'placeOfReceiptOfGood',
        'portOfLoading', 'portOfDischarge', 'placeOfDeliveryWithStateCode',
        'containerNum', 'customSeal', 'marks',
        'fullCommondityDescription', 'placeOfIssueOfCargo',
        'exporterName', 'NameOfAuthorised'
        ]

        for field in fields_to_uppercase:
            value = cleaned_data.get(field)
            if value:
                cleaned_data[field] = str(value).upper()

        return cleaned_data

jobACD/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import HttpResponse, get_object_or_404, render
from django.urls import reverse_lazy
from django.views import generic
from jobACD.forms import AcdForm
from jobACD.models import AcdModel
from stuffingSheet.models import StuffingSheetModel

# Create your views here.

## Class Based Views....

class ACDformDetails(LoginRequiredMixin, generic.DetailView):
    model = AcdModel
    login_url = '/login/'
    redirect_field_name = 'jobACD/acdmodel_detail.html'
    context_object_name = 'acdFormDetail'

class ACDformList(LoginRequiredMixin, generic.ListView):
    model = AcdModel
    context_object_name = 'acdList'
    template_name = 'jobACD/acdmodel_list.html'

class ACDformUpdate(LoginRequiredMixin, generic.UpdateView):
    model = AcdModel
    form_class = AcdForm
    login_url = '/login/'
    redirect_field_name = 'jobACD/acdmodel_detail.html'

    def form_valid(self, form):
        response = super().form_valid(form)
        data_of_job_instance = self.object.index

        StuffingSheetModel.objects.update_or_create(
            index=data_of_job_instance,
            defaults={
                'customSeal' : self.object.customSeal,
            }
        )

        return response
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Fetch unique exporter info from the database and add them to the context
        context['unique_consignee'] = AcdModel.objects.values_list('consignee', flat=True).distinct()
        context['unique_exporterAddress'] = AcdModel.objects.values_list('exporterAddress', flat=True).distinct()
        context['unique_bookingNum'] = AcdModel.objects.values_list('bookingNum', flat=True).distinct()
        context['unique_shippingBillNo'] = AcdModel.objects.values_list('shippingBillNo', flat=True).distinct()
        context['unique_customSeal'] = AcdModel.objects.values_list('customSeal', flat=True).distinct()

        return context

class AcdTemplate(LoginRequiredMixin, generic.DetailView):
    model = AcdModel
    login_url = '/login/'
    template_name = 'jobACD/acdTemplate.html'
    context_object_name = 'acdForm'

    def get_queryset(self):
        return AcdModel.objects.filter(pk=self.kwargs['pk'])

def search_view(request):
    query = request.GET.get('search', '')
    
    search_fields = [
    'exporterName',
    'consignee',
    'bookingNum',
    'containerNum',
]

    # Create an empty Q object to accumulate conditions
    query_conditions = Q()

    # Loop through each field and add an OR condition
    for field in search_fields:
        query_conditions |= Q(**{f'{field}__icontains': query})

    # Use the accumulated Q object in the filter
    results = AcdModel.objects.filter(query_conditions)

    return render(request, 'jobACD/search.html', {'results': results})


    

jobACD/templates/jobACD/acdTemplate.html
{% extends 'base.html' %}

{% block content %}

    <center><b><u><h1>{{ acdForm.exporterName }}</h1></u></b></center>
    <center><h6>{{ acdForm.exporterAddress }}</h6></center>

    <br>
    <center><b><h6><u>DATA ELEMENTS IN THE ADVANCE CARGO DECLARATION</u></h6></b></center>

    <div class="container">
        <table class="table mx-auto p-2" style="width: 900px;">
            <tbody>
                <tr>
                    <td class="border border-0" style="width: 50%;">01. Booking No. Assigned by Ocean Carrier</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.bookingNum }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">02. Shipper (Full Address)</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.exporterAddress }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">03. Consignee (Full Address with ZipCode)</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.consignee }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">04. Name of Ocean Carrier</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;"></td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">05. Vessel Name of Voy No.</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;"></td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">06. Place of Receipt</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.placeOfReceiptOfGood }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">07. Port of Loading</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.portOfLoading }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">08. Port of Discharge</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.portOfDestination }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">09. Place Of Delivery With State Code</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.finalDestination }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">10. Container Number</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.containerNum }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">11. Seal Number [s]</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.customSeal }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">12. Shipping Bill No</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.shippingBillNo }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">13. Cargo Marks and Numbers</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.marks }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">14. Number and Type of Packages</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.noOfPkgs }}  CASES</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">15. Full Commodity Description</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.fullCommondityDescription }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">16. Gross Weight of Cargo [Kilos]</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.grossWt }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">17. HTS Code [6 Digit]</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.htsCode }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">18. Place of Issue of Cargo Declaration</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.placeOfIssueOfCargo }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">19. Date of Issue of Cargo Declaration</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.dateOfIssueOfCargo|date:"d-m-Y" }}</td>
                </tr>
                
                <tr>
                    <td colspan="2" class="border border-0">
                        <p>The owner of the cargo certificate that the particulars described above are true and complete to their best information and belief</p>
                    </td>
                </tr>
                
                <tr>
                    <td class="border border-0" style="width: 50%;">20. Name of Shipper</td>
                    <td class="border border-0" style="width: 25%;">:</td>
                    <td class="border border-0" style="width: 25%;">{{ acdForm.exporterName }}</td>
                </tr>
                <tr>
                    <td class="border border-0" style="width: 50%;">21. Name of Person Singing and Signature</td>
                    <td class="border border-0" style="width: 25%;">:   {{ acdForm.NameOfAuthorised }}</td>
                    <td><img src="{{ acdForm.signatureImg.url }}" alt="image" height="=30%" width="40%"></td>
                </tr>
            </tbody>    
        </table>
    </div>


{% endblock %}

jobACD/templates/jobACD/acdmodel_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>Details of Job: {{ acdFormDetail.jobNumber }}</h2>

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  <a href="{% url 'jobACD:acdUpdate' pk=acdFormDetail.pk %}"><button class="btn btn-success me-md-2" type="button">Update</button></a>
</div>

<br>

<form method="GET" class="d-grid gap-2 d-md-flex justify-content-md-end" action="{% url 'jobACD:acdTemplate' pk=acdFormDetail.pk %}">
    <button class="btn btn-outline-success" type="submit">Create ACD</button>
</form>
<hr>
<br>
<!-- showJobDetail -->
<h4>For Job:</h4>

<table class="table table-striped">
    <thead>
        <tr>
            <th style="width: 20%;" scope="col ">jobNumber</th>
            <th style="width: 20%;" scope="col ">bookingNum</th>
            <th style="width: 20%;" scope="col ">exporterName</th>
            <th style="width: 20%;" scope="col ">consignee</th>
            <th style="width: 20%;" scope="col ">nameOfOceanCarrier</th>
            <th style="width: 20%;" scope="col ">exporterName</th>
            <th style="width: 20%;" scope="col ">placeOfReceiptOfGood</th>
            <th style="width: 20%;" scope="col ">portOfLoading</th>
            <th style="width: 20%;" scope="col ">portOfDestination</th>
            <th style="width: 20%;" scope="col ">finalDestination</th>
            <th style="width: 20%;" scope="col ">containerNum</th>
            <th style="width: 20%;" scope="col ">shippingBillNo</th>
            <th style="width: 20%;" scope="col ">noOfPkgs</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ acdFormDetail.jobNumber }}</td>
            <td>{{ acdFormDetail.bookingNum }}</td>
            <td>{{ acdFormDetail.exporterName }}</td>
            <td>{{ acdFormDetail.consignee }}</td>
            <td>{{ acdFormDetail.nameOfOceanCarrier }}</td>
            <td>{{ acdFormDetail.exporterName }}</td>
            <td>{{ acdFormDetail.placeOfReceiptOfGood }}</td>
            <td>{{ acdFormDetail.portOfLoading }}</td>
            <td>{{ acdFormDetail.portOfDestination }}</td>
            <td>{{ acdFormDetail.finalDestination }}</td>
            <td>{{ acdFormDetail.containerNum }}</td>
            <td>{{ acdFormDetail.shippingBillNo }}</td>
            <td>{{ acdFormDetail.noOfPkgs }}</td>            
        </tr>
    </tbody>
</table>

<br>

{% endblock %}

jobACD/templates/jobACD/acdmodel_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<br>
<h5 class="display">ACD Form</h5>
    <div  style="height: 60vh;">
        <form method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            {% bootstrap_form form %}

            <input type="submit" value="Update" class="btn btn-primary pd-10">
        </form>
        <br><br><br><br><br>
    </div>

{% include 'bases/jobAcdBase.html' %}

{% endblock %}

jobACD/templates/jobACD/acdmodel_list.html
{% extends 'base.html' %}

{% block content %}
<form method="GET" action="{% url 'jobACD:search' %}" class="d-flex" role="search">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" id="search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
<br>

<br>
<h2>List of the job</h2>

<br>
<!-- showList -->
<table class="table table-striped">
    <thead>
      <tr>
        <tr>
            <th style="width: 20%;" scope="col ">Index</th>
            <th style="width: 20%;" scope="col ">Job Number</th>
            <th style="width: 20%;" scope="col ">Exporter Name</th>
            <th style="width: 20%;" scope="col ">Consignee</th>
            <th style="width: 20%;" scope="col ">Booking No</th>
            <th style="width: 20%;" scope="col ">Container Num</th>
            <th style="width: 20%;" scope="col ">Port Of Loading</th>
          </tr>
    </thead>
    <tbody>
        {% for items in acdList %}
        <tr>
            <td><a href="{% url 'jobACD:acdDetail' pk=items.pk %}">{{ items.index }}</a></td>
            <td>{{ items.jobNumber }}</td>
            <td>{{ items.exporterName }}</td>
            <td>{{ items.consignee }}</td>
            <td>{{ items.bookingNum }}</td>
            <td>{{ items.containerNum }}</td>
            <td>{{ items.portOfLoading }}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>


{% endblock %}

jobACD/templates/jobACD/search.html
{% extends 'base.html' %}

{% block content %}

<h1>Searched Results</h1>
<hr>
    {% if results %}
    <table class="table table-striped">
        <thead>
          <tr>
            <th style="width: 20%;" scope="col ">Exporter Name</th>
            <th style="width: 20%;" scope="col ">Consignee</th>
            <th style="width: 20%;" scope="col ">Booking No</th>
            <th style="width: 20%;" scope="col ">Port Of Loading</th>
            <th style="width: 20%;" scope="col ">Port Of Destination</th>
          </tr>
        </thead>
        <tbody>
            {% for job in results %}
            <tr>
              <td><a href="{% url 'jobBOL:bolDetail' pk=job.pk %}">{{ job.exporterName }}</a></td>
              <td>{{ job.consignee }}</td>
              <td>{{ job.bookingNum }}</td>
              <td>{{ job.portOfLoading }}</td>
              <td>{{ job.portOfDestination }}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No results found.</p>
    {% endif %}

{% endblock %}