ARMproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('entry/', views.Entry.as_view(), name='entry'), # after login where to go url.
    path('exit/', views.Exit.as_view(), name='exit'), # after logout where to go url.

    ## jobData App...
    path('jobData/', include('jobData.urls'), name='jobData'),

    ## jobVGM App...
    path('jobVGM/', include('jobVGM.urls'), name='jobVGM'),

    ## jobBOL App...
    path('jobBOL/', include('jobBOL.urls'), name='jobBOL'),

    ## jobACD App...
    path('jobACD/', include('jobACD.urls'), name='jobACD'),

    ## stuffingSheet App...
    path('stuffingSheet/', include('stuffingSheet.urls'), name='stuffingSheet'),

    ## jobOther App...
    path('jobOther/', include('jobOther.urls'), name='jobOther'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

jobACD/urls.py
from django.urls import path

from . import views

app_name = 'jobACD'

urlpatterns = [
    path('list', views.ACDformList.as_view(), name='acdList'),
    path('<int:pk>', views.ACDformDetails.as_view(), name='acdDetail'),
    path('<int:pk>/update', views.ACDformUpdate.as_view(), name='acdUpdate'),
    path('<int:pk>/acdForm/', views.AcdTemplate.as_view(), name='acdTemplate'),
    
    ## Function based Views...
    path('list/search/', views.search_view, name='search'),
]

jobVGM/urls.py
from django.urls import path
from . import views

app_name = 'jobVGM'

urlpatterns = [
    # path('', views.VGMformView.as_view(), name='vgmForm'),
    path('list', views.VGMformList.as_view(), name='vgmList'),
    path('<int:pk>', views.VGMformDetails.as_view(), name='vgmDetail'),
    path('<int:pk>/update', views.VGMformUpdate.as_view(), name='vgmUpdate'),

    ## Function based Views...
    path('list/search/', views.search_view, name='search'),

    ## VGM Type form urls...
    path('type1/<int:pk>/form1', views.VgmForm1Detail.as_view(), name='type1Detail'),
    path('type2/<int:pk>/form2', views.VgmForm2Detail.as_view(), name='type2Detail'),
    path('type3/<int:pk>/form3', views.VgmForm3Detail.as_view(), name='type3Detail'),
    path('type4/<int:pk>/form4', views.VgmForm4Detail.as_view(), name='type4Detail'),
]

jobVGM/models.py
from datetime import date

from django.db import models
from django.urls import reverse
from jobData.models import DataOfJob

# Create your models here.

class VgmModel(models.Model):

    PERMISSIBLE_WEIGHT_CHOICES = [
        (32500, '32,500 lbs'),
        (32450, '32,450 lbs'),
    ]

    index = models.ForeignKey(DataOfJob, on_delete=models.CASCADE, primary_key=True)
    jobNumber = models.IntegerField(blank=True, null=True)
    exporterName = models.CharField(max_length=255, blank=True)
    exporterAddress = models.CharField(max_length=255, blank=True)
    IEC_no = models.IntegerField(blank=True, null=True)
    NameOfAuthorised = models.CharField(max_length=255, blank=True)
    bookingNum = models.CharField(max_length=255, blank=True)
    DesignationOfAuthorised = models.CharField(max_length=255, blank=True)
    contactDetail = models.IntegerField(blank=True, null=True)
    containerNum = models.CharField(max_length=255, blank=True)
    size_20 = models.BooleanField('size=20', default=False)
    size_40 = models.BooleanField('size=40', default=False)
    permissibleWeight = models.IntegerField(blank=True, null=True, choices=PERMISSIBLE_WEIGHT_CHOICES)
    WeighBridgeRegistration = models.CharField(max_length=255, blank=True)
    WeighBridgeAddress = models.CharField(max_length=255, blank=True)
    emptyContainerMass = models.FloatField(blank=True, null=True)
    goodMass = models.FloatField(blank=True, null=True)
    dateOfWeigh = models.DateField(blank=True, null=True)
    timeofWeigh = models.TimeField(blank=True, null=True)
    cargoWeight = models.IntegerField(blank=True, null=True)
    containerWeight = models.IntegerField(blank=True, null=True)
    verifiedGrossMass = models.FloatField(blank=True, null=True)
    weightmentSlipNum = models.CharField(max_length=255, blank=True)
    unitOfMeasure = models.CharField(max_length=255, blank=True)
    typeOF = models.CharField(max_length=255, default='NA', blank=True)
    ifHazardous = models.CharField(max_length=255, default='NA', blank=True)
    signatureImg = models.ImageField(upload_to='signature_pic/%y', blank=True, null=True)
    todayDate = models.DateField(default=date.today)
    vesselName = models.CharField(max_length=255, blank=True, null=True, default='NA')
    vcnNo = models.CharField(max_length=255, blank=True, null=True, default='NA')

    def save(self, *args, **kwargs):
        if self.cargoWeight is not None and self.containerWeight is not None:
            self.verifiedGrossMass = self.cargoWeight + self.containerWeight
        else:
            self.verifiedGrossMass = None

        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.index)
    
    def get_absolute_url(self):
        return reverse('jobVGM:vgmDetail', kwargs={'pk': self.pk})

jobVGM/forms.py
from dal import autocomplete
from django import forms
from django.forms import ModelForm

from .models import VgmModel


class BillingForm(ModelForm):

    ## Field Custom Name....
    jobNumber = forms.IntegerField(required=False, label='Job Number')
    exporterName = forms.CharField(required=False, label='Exporter Name')
    exporterAddress = forms.Textarea()
    IEC_no = forms.IntegerField(required=False, label='IEC No')
    NameOfAuthorised = forms.CharField(required=False, label='Name Of Authorised')
    bookingNum = forms.CharField(required=False, label='Booking No')
    DesignationOfAuthorised = forms.CharField(required=False, label='Designation Of Authorised')
    contactDetail = forms.IntegerField(required=False, label='Contact Detail')
    containerNum = forms.CharField(required=False, label='Container No')
    WeighBridgeRegistration = forms.CharField(required=False, label='WeighBridge Registration')
    WeighBridgeAddress = forms.CharField(required=False, label='WeighBridge Address')
    emptyContainerMass = forms.FloatField(required=False, label='Empty Container Mass')
    goodMass = forms.FloatField(required=False, label='Good Mass')
    dateOfWeigh = forms.DateField(required=False, label='Date of WEigh')
    timeofWeigh = forms.TimeField(required=False, label='Time of WEigh(Hr:Min)')
    cargoWeight = forms.IntegerField(required=False, label='Cargo Weight')
    containerWeight = forms.IntegerField(required=False, label='Container Weight')
    verifiedGrossMass = forms.FloatField(required=False, label='Verified Gross Mass')
    weightmentSlipNum = forms.CharField(required=False, label='Weightment Slip No')
    unitOfMeasure = forms.CharField(required=False, label='Unit Of Measure')
    typeOF = forms.CharField(required=False, label='Type Of')
    ifHazardous = forms.CharField(required=False, label='If Hazardous')
    vesselName = forms.CharField(required=False, label='Vessel Name')
    vcnNo = forms.CharField(required=False, label='Vcn No')

    
    widget=forms.TextInput(attrs={'placeholder': None})
    
    class Meta:
        model = VgmModel
        exclude = ['verifiedGrossMass', 'todayDate']
        # fields = '__all__'
        widgets = {
            'timeofWeigh' : forms.DateInput(attrs={'type':'time'}),
            'dateOfWeigh': forms.DateInput(attrs={'type':'date'}),
            'exporterAddress': forms.Textarea(attrs={'rows': 5}),
            'size_20': forms.CheckboxInput(),
            'size_40': forms.CheckboxInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['dateOfWeigh'].input_formats = ["%Y-%m-%d"]
        self.fields['dateOfWeigh'].label = 'Date Of Weigh'
        self.fields['timeofWeigh'].input_formats = ["%H-%m"]
        self.fields['timeofWeigh'].label = 'Time of Weigh'

    def __init__(self, *args, **kwargs):
        super(BillingForm, self).__init__(*args, **kwargs)

        # Pre-select the exporterName field with the value from the instance
        instance = getattr(self, 'instance', None)
        if instance and instance.exporterName:
            self.fields['exporterName'].queryset = VgmModel.objects.filter(exporterName=instance.exporterName)
            self.fields['exporterName'].initial = instance.exporterName
        else:
            self.fields['exporterName'].queryset = VgmModel.objects.none()
    
    def clean(self):
        cleaned_data = super().clean()

        fields_to_uppercase = [
            'exporterName', 'exporterAddress', 'NameOfAuthorised', 'bookingNum',
            'DesignationOfAuthorised', 'containerNum', 'WeighBridgeRegistration',
            'WeighBridgeAddress', 'weightmentSlipNum', 'unitOfMeasure', 'typeOF',
            'ifHazardous', 'vesselName', 'vcnNo'
        ]

        for field in fields_to_uppercase:
            value = cleaned_data.get(field)
            if field is not None:
                cleaned_data[field] = str(value).upper()

jobVGM/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import HttpResponse, render
from django.urls import reverse_lazy
from django.views import generic
from jobACD.models import AcdModel
from jobBOL.models import BolModel
from jobOther.models import OtherModel
from jobVGM.forms import BillingForm
from jobVGM.models import VgmModel
from stuffingSheet.models import StuffingSheetModel

# Create your views here.

## Class Based Views....

class VGMformDetails(LoginRequiredMixin, generic.DetailView):
    model = VgmModel
    login_url = '/login/'
    redirect_field_name = 'jobVGM/vgmmodel_detail.html'
    context_object_name = 'vgmFormDetail'
    

class VGMformList(LoginRequiredMixin, generic.ListView):
    model = VgmModel
    context_object_name = 'vgmList'
    template_name = 'jobVGM/vgmmodel_list.html'

class VGMformUpdate(LoginRequiredMixin, generic.UpdateView):
    model = VgmModel
    form_class = BillingForm
    login_url = '/login/'
    redirect_field_name = 'jobVGM/vgmmodel_detail.html'

    def form_valid(self, form):
        response = super().form_valid(form)  # Save the VgmModel instance

        # Get the related DataOfJob instance using the foreign key 'index'
        data_of_job_instance = self.object.index  # Assuming 'data_of_job' is the foreign key field in VgmModel

        # Update related models using 'index' from DataOfJob
        BolModel.objects.update_or_create(
            index=data_of_job_instance,  # Assuming BolModel has a foreign key to DataOfJob
            defaults={
                'jobNumber' : self.object.jobNumber,
                'exporterName': self.object.exporterName,
                'exporterAddress': self.object.exporterAddress,
                'IECno': self.object.IEC_no,
                'bookingNum': self.object.bookingNum,
                'containerNum': self.object.containerNum,
                'vesselName': self.object.vesselName,
            }
        )

        AcdModel.objects.update_or_create(
            index=data_of_job_instance,
            defaults={
                'jobNumber' : self.object.jobNumber,
                'exporterName': self.object.exporterName,
                'exporterAddress': self.object.exporterAddress,
                'containerNum' : self.object.containerNum,
                'vesselName' : self.object.vesselName,
                'NameOfAuthorised' : self.object.NameOfAuthorised,
                'signatureImg' : self.object.signatureImg,
            }
        )

        StuffingSheetModel.objects.update_or_create(
            index=data_of_job_instance,
            defaults={
                'jobNumber' : self.object.jobNumber,
                'exporterName': self.object.exporterName,
                'bookingNum' : self.object.containerNum,
                'containerNum' : self.object.containerNum,
                'size_20': self.object.size_20,
                'size_40': self.object.size_40,
            }
        )

        OtherModel.objects.update_or_create(
            index=data_of_job_instance,
            defaults={
                'jobNumber' : self.object.jobNumber,
                'containerNum' : self.object.containerNum,
                'bookingNum' : self.object.containerNum,
            }
        )

        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Fetch unique Exporter info from the database and add them to the context
        context['unique_exporterName'] = VgmModel.objects.values_list('exporterName', flat=True).distinct()
        context['unique_exporterAddress'] = VgmModel.objects.values_list('exporterAddress', flat=True).distinct()
        context['unique_NameOfAuthorised'] = VgmModel.objects.values_list('NameOfAuthorised', flat=True).distinct()
        context['unique_DesignationOfAuthorised'] = VgmModel.objects.values_list('DesignationOfAuthorised', flat=True).distinct()
        context['unique_contactDetail'] = VgmModel.objects.values_list('contactDetail', flat=True).distinct()
        context['unique_bookingNum'] = VgmModel.objects.values_list('bookingNum', flat=True).distinct()

        return context
    
#__________________________________________________________________________________
## Different VGM forms using Class Based Views....
# For Hapag, Cosco, ....HMM.
class VgmForm1Detail(LoginRequiredMixin, generic.DetailView):
    model = VgmModel
    login_url = '/login/'
    template_name = 'jobVGM/vgm_type1.html'
    context_object_name = 'vgmForm1'

    def get_queryset(self):
        return VgmModel.objects.filter(pk=self.kwargs['pk'])

# For MSC.
class VgmForm2Detail(LoginRequiredMixin, generic.DetailView):
    model = VgmModel
    login_url = '/login/'
    template_name = 'jobVGM/vgm_type2.html'
    context_object_name = 'vgmForm2'

    def get_queryset(self):
        return VgmModel.objects.filter(pk=self.kwargs['pk'])

# For CMA, ANL.
class VgmForm3Detail(LoginRequiredMixin, generic.DetailView):
    model = VgmModel
    login_url = '/login/'
    template_name = 'jobVGM/vgm_type3.html'
    context_object_name = 'vgmForm3'

    def get_queryset(self):
        return VgmModel.objects.filter(pk=self.kwargs['pk'])

# For Evergreen Line.
class VgmForm4Detail(LoginRequiredMixin, generic.DetailView):
    model = VgmModel
    login_url = '/login/'
    template_name = 'jobVGM/vgm_type4.html'
    context_object_name = 'vgmForm4'

    def get_queryset(self):
        return VgmModel.objects.filter(pk=self.kwargs['pk'])

#_________________________________________________________________________________

## Function based views....

def search_view(request):
    query = request.GET.get('search', '') 
    
    search_fields = [
    'exporterName',
    'IEC_no',
    'NameOfAuthorised',
    'DesignationOfAuthorised',
    'containerNum',
    'bookingNum'
]

    # Create an empty Q object to accumulate conditions
    query_conditions = Q()

    # Loop through each field and add an OR condition
    for field in search_fields:
        query_conditions |= Q(**{f'{field}__icontains': query})

    # Use the accumulated Q object in the filter
    results = VgmModel.objects.filter(query_conditions)

    return render(request, 'jobVGM/search.html', {'results': results})

jobVGM/templates/jobVGM/search.html
{% extends 'base.html' %}

{% block content %}

<h1>Searched Results</h1>
<hr>
    {% if results %}
    <table class="table table-striped">
        <thead>
          <tr>
            <th style="width: 20%;" scope="col ">Exporter Name</th>
            <th style="width: 20%;" scope="col ">Exporter Address</th>
            <th style="width: 20%;" scope="col ">IEC no</th>
            <th style="width: 20%;" scope="col ">Signature</th>
            <th style="width: 20%;" scope="col ">Today Date</th>
          </tr>
        </thead>
        <tbody>
            {% for job in results %}
            <tr>
              <td><a href="{% url 'jobVGM:vgmDetail' pk=job.pk %}">{{ job.exporterName }}</a></td>
              <td>{{ job.exporterAddress }}</td>
              <td>{{ job.IEC_no }}</td>
    
              {% if job.signatureImg and vgmFormDetail.signatureImg.url %}
                <td><img src="{{ job.signatureImg.url }}" alt="image" height="=20%" width="20%" class="img-thumbnail"></td>
              {% else %}
                <td><img src="#" alt="image" height="=20%" width="20%" class="img-thumbnail"></td>
              {% endif %}
              <td>{{ job.todayDate }}</td>
    
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No results found.</p>
    {% endif %}

{% endblock %}

jobVGM/templates/jobVGM/vgmmodel_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>Details of Job: {{ vgmFormDetail.jobNumber }}</h2>

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  <a href="{% url 'jobVGM:vgmUpdate' pk=vgmFormDetail.pk %}"><button class="btn btn-success me-md-2" type="button">Update</button></a>
</div>

<hr>
<br>
<!-- vgmFormDetail -->
<h4>For Job:</h4>

<table class="table table-striped">
    <thead>
      <tr>
        <th style="width: 20%;" scope="col ">Job Number</th>
        <th style="width: 20%;" scope="col ">Exporter Name</th>
        <th style="width: 20%;" scope="col ">IEC no</th>
        <th style="width: 20%;" scope="col ">Name Of Authorised</th>
        <th style="width: 20%;" scope="col ">Booking Num</th>
        <th style="width: 20%;" scope="col ">Designation Of Authorised</th>
        <th style="width: 20%;" scope="col ">Contact Detail</th>
        <th style="width: 20%;" scope="col ">Container Num</th>
        <th style="width: 20%;" scope="col ">Size_20</th>
        <th style="width: 20%;" scope="col ">Size_40</th>
        <th style="width: 20%;" scope="col ">Permissible Weight</th>
        <th style="width: 20%;" scope="col ">Weigh Bridge Registration</th>
        <th style="width: 20%;" scope="col ">Weigh Bridge Address</th>
        <th style="width: 20%;" scope="col ">Cargo Weight</th>
        <th style="width: 20%;" scope="col ">Container Weight</th>
        <th style="width: 20%;" scope="col ">Verified Gross Mass</th>
        <th style="width: 20%;" scope="col ">Signature</th>
        <th style="width: 20%;" scope="col ">Date</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td>{{ vgmFormDetail.jobNumber}}</td>
          <td>{{ vgmFormDetail.exporterName}}</td>
          <td>{{ vgmFormDetail.IEC_no}}</td>
          <td>{{ vgmFormDetail.NameOfAuthorised}}</td>
          <td>{{ vgmFormDetail.bookingNum}}</td>
          <td>{{ vgmFormDetail.DesignationOfAuthorised}}</td>
          <td>{{ vgmFormDetail.contactDetail}}</td>
          <td>{{ vgmFormDetail.containerNum}}</td>

          {% if vgmFormDetail.size_20 == True and vgmFormDetail.size_40 == True %}
            <td>20</td>
            <td>40</td>
          {% elif vgmFormDetail.size_20 == True and vgmFormDetail.size_40 == False %}
            <td>20</td>
            <td>0</td>
          {% elif vgmFormDetail.size_20 == False and vgmFormDetail.size_40 == True %}
            <td>0</td>
            <td>40</td>
          {% endif %}
          
          <td>{{ vgmFormDetail.permissibleWeight}}</td>
          <td>{{ vgmFormDetail.WeighBridgeRegistration}}</td>
          <td>{{ vgmFormDetail.WeighBridgeAddress}}</td>
          <td>{{ vgmFormDetail.cargoWeight}}</td>
          <td>{{ vgmFormDetail.containerTireWeight}}</td>
          <td>{{ vgmFormDetail.verifiedGrossMass}}</td>


          {% if vgmFormDetail.signatureImg and vgmFormDetail.signatureImg.url %}
            <td><img src="{{ vgmFormDetail.signatureImg.url }}" alt="image" height="=90%" width="90%"></td>
          {% else %}
            <td><img src="#" alt="image" height="=20%" width="20%" class="img-thumbnail"></td>
          {% endif %}
          <td>{{ vgmFormDetail.todayDate|date:"d-m-Y" }}</td>
        </tr>
    </tbody>
</table>

<br>
<div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    VGM List
  </a>
  {% if vgmFormDetail.signatureImg %}
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'jobVGM:type1Detail' pk=vgmFormDetail.pk %}">HaPag</a></li>
    <li><a class="dropdown-item" href="{% url 'jobVGM:type1Detail' pk=vgmFormDetail.pk %}">CosCo</a></li>
    <li><a class="dropdown-item" href="{% url 'jobVGM:type1Detail' pk=vgmFormDetail.pk %}">oocL</a></li>
    <li><a class="dropdown-item" href="{% url 'jobVGM:type1Detail' pk=vgmFormDetail.pk %}">MSK</a></li>
    <li><a class="dropdown-item" href="{% url 'jobVGM:type1Detail' pk=vgmFormDetail.pk %}">Bayline</a></li>
    <li><a class="dropdown-item" href="{% url 'jobVGM:type1Detail' pk=vgmFormDetail.pk %}">SCI</a></li>
    <li><a class="dropdown-item" href="{% url 'jobVGM:type1Detail' pk=vgmFormDetail.pk %}">Hamburg Sud</a></li>
    <li><a class="dropdown-item" href="{% url 'jobVGM:type1Detail' pk=vgmFormDetail.pk %}">HMM</a></li>
    <li><a class="dropdown-item" href="{% url 'jobVGM:type2Detail' pk=vgmFormDetail.pk %}">MSC</a></li>  <!-- This is of different format and "MSK" is of different format -->
    <li><a class="dropdown-item" href="{% url 'jobVGM:type3Detail' pk=vgmFormDetail.pk %}">CMA</a></li>
    <li><a class="dropdown-item" href="{% url 'jobVGM:type3Detail' pk=vgmFormDetail.pk %}">ANL</a></li>
    <li><a class="dropdown-item" href="{% url 'jobVGM:type4Detail' pk=vgmFormDetail.pk %}">Evergreen Line</a></li>
  </ul>
  {% endif %}
</div>
{% endblock %}

jobVGM/templates/jobVGM/vgmmodel_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<br>
<h5 class="display">VGM Form</h5>
    <div  style="height: 60vh;">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}

            <input type="submit" value="Update" class="btn btn-primary pd-10">
        </form>
        <br><br><br><br><br>
    </div>
 <!-- ------------------------------------------------------------------------------------- -->
    <script>
        function copyToClipboard(value) {
            var tempInput = document.createElement("input");
            tempInput.style.position = "absolute";
            tempInput.style.left = "-1000px";
            tempInput.value = value;
            document.body.appendChild(tempInput);
            tempInput.select();
            document.execCommand("copy");
            document.body.removeChild(tempInput);
        }
        </script>

{% include 'bases/jobVgmBase.html' %}

{% endblock %}

jobVGM/templates/jobVGM/vgmmodel_list.html
{% extends 'base.html' %}

{% block content %}
<form method="GET" action="{% url 'jobVGM:search' %}" class="d-flex" role="search">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" id="search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
<br>

<h2>List of the job</h2>

<br>
<!-- showList -->
<table class="table table-striped">
    <thead>
      <tr>
        <th style="width: 20%;" scope="col">Index</th>
        <th style="width: 20%;" scope="col">Job Number</th>
        <th style="width: 20%;" scope="col">Exporter Name</th>
        <th style="width: 20%;" scope="col">IEC_no</th>
        <th style="width: 20%;" scope="col">Name Of Authorised</th>
        <th style="width: 20%;" scope="col">Designation Of Authorised</th>
        <th style="width: 20%;" scope="col">Container Num</th>
        
      </tr>
    </thead>
    <tbody>
        {% for items in vgmList %}
            <tr>
                <td><a href="{% url 'jobVGM:vgmDetail' pk=items.pk %}" class="link-opacity-25-hover">{{ items.index }}</a></td>
                <td>{{ items.jobNumber }}</td>
                <td>{{ items.exporterName }}</td>
                <td>{{ items.IEC_no }}</td>
                <td>{{ items.NameOfAuthorised }}</td>
                <td>{{ items.DesignationOfAuthorised }}</td>
                <td>{{ items.containerNum }}</td>
            </tr>
        {% endfor %}
    </tbody>
  </table>


{% endblock %}